// frontend4/src/components/TimePicker.svelte
<script lang="ts">
  import { onMount, createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();
  const currentTime = new Date();
  let hour = currentTime.getHours();
  let minute = currentTime.getMinutes();
  let second = currentTime.getSeconds();

  const formatTime = (t: number) => {
    let formatted: number | string = t;
    if (t < 10) {
      formatted = `0${t}`;
    }
    return formatted;
  };

  $: time = `${formatTime(hour)}:${formatTime(minute)}:${formatTime(second)}`;

  onMount(() => {
    dispatch('timeChanged', { time });
  });

  $: dispatch('timeChanged', { time });

  const hourChange = e => {
    if (+e.target.value > 23) {
      hour = 23;
    } else if (+e.target.value < 0) {
      hour = 0;
    } else if (e.target.value === '') {
      hour = 0;
    } else {
      hour = +e.target.value;
    }
  };

  const minuteChange = e => {
    if (+e.target.value > 59) {
      minute = 59;
    } else if (+e.target.value < 0) {
      minute = 0;
    } else if (e.target.value === '') {
      minute = 0;
    } else {
      minute = +e.target.value;
    }
  };

  const secondChange = e => {
    if (+e.target.value > 59) {
      second = 59;
    } else if (+e.target.value < 0) {
      second = 0;
    } else if (e.target.value === '') {
      second = 0;
    } else {
      second = +e.target.value;
    }
  };

  const hourUp = () => {
    hour++;
    if (hour > 23) {
      hour = 0;
    }
    time = `${formatTime(hour)}:${formatTime(minute)}:${formatTime(second)}`;
  };
  const hourDown = () => {
    hour--;
    if (hour < 0) {
      hour = 23;
    }
  };

  const minuteUp = () => {
    minute++;
    if (minute > 59) {
      minute = 0;
      hourUp();
    }
  };
  const minuteDown = () => {
    minute--;
    if (minute < 0) {
      minute = 59;
      hourDown();
    }
  };

  const secondUp = () => {
    second++;
    if (second > 59) {
      second = 0;
      minuteUp();
    }
  };
  const secondDown = () => {
    second--;
    if (second < 0) {
      second = 59;
      minuteDown();
    }
  };
</script>

<div class="timePicker" data-time={time}>
  <div class="hour">
    <div role="textbox" on:click={hourUp} class="hrUp" />
    <input
      placeholder="00"
      type="number"
      class="hr"
      bind:value={hour}
      onChange={hourChange}
    />
    <div on:click={hourDown} class="hrDown" />
  </div>

  <div class="separator">:</div>

  <div class="minute">
    <div on:click={minuteUp} class="minUp" />
    <input
      placeholder="00"
      type="number"
      class="min"
      value={minute}
      onChange={minuteChange}
    />
    <div on:click={minuteDown} class="minDown" />
  </div>

  <div class="separator">:</div>

  <div class="second">
    <div role="textbox" on:click={secondUp} class="secUp" />
    <input
      placeholder="00"
      type="number"
      class="sec"
      value={second}
      onChange={secondChange}
    />
    <div role="textbox" on:click={secondDown} class="secDown" />
  </div>
</div>

<style>
  input[type='number']::-webkit-outer-spin-button,
  input[type='number']::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
    color: hsl(0, 0%, 100%);
  }

  input[type='number'] {
    -moz-appearance: textfield;
    color: hsl(0, 0%, 100%);
  }

  .timePicker {
    display: flex;
    justify-content: space-around;
    align-items: center;
    width: 100%;
    max-width: 200px;
    margin: 0 auto;
    padding: 25px 15px;
    background-color: transparent;
    color: hsl(0, 0%, 100%);
    font-size: 20px;
    font-weight: 700;
    user-select: none;
  }

  .timePicker .hour,
  .timePicker .minute,
  .timePicker .second {
    position: relative;
    min-width: 60px;
    text-align: center;
    display: flex;
    justify-content: stretch;
    align-items: stretch;
  }

  .timePicker .hour .hr,
  .timePicker .minute .min,
  .timePicker .second .sec {
    background: none;
    font-size: 20px;
    appearance: none;
    border: none;
    outline: none;
    display: block;
    width: 100%;
    text-align: center;
  }

  .timePicker .hour .hrUp,
  .timePicker .hour .hrDown,
  .timePicker .minute .minUp,
  .timePicker .minute .minDown,
  .timePicker .second .secUp,
  .timePicker .second .secDown {
    position: absolute;
    left: 50%;
    transform: translateX(-50%);
    width: 15px;
    height: 20px;
    border-left: 15px solid transparent;
    border-right: 15px solid transparent;
    cursor: pointer;
  }

  .timePicker .hour .hrUp,
  .timePicker .minute .minUp,
  .timePicker .second .secUp {
    top: -15px;
    border-bottom: 15px solid hsl(0, 0%, 100%);
  }

  .timePicker .hour .hrDown,
  .timePicker .minute .minDown,
  .timePicker .second .secDown {
    bottom: -17px;
    border-top: 15px solid hsl(0, 0%, 100%);
  }

  .timePicker .hour .hrUp:hover,
  .timePicker .hour .hrDown:hover,
  .timePicker .minute .minUp:hover,
  .timePicker .minute .minDown:hover,
  .timePicker .second .secUp:hover,
  .timePicker .second .secDown:hover {
    border-bottom-color: #53565a;
    border-top-color: #53565a;
  }
</style>

// frontend/src/components/timePicker.tsx
/* eslint-disable jsx-a11y/control-has-associated-label */
/* eslint-disable jsx-a11y/click-events-have-key-events */
import React, { useEffect, useRef, useState } from 'react'
import styles from '../css/timePicker.module.css'
import { formatTime } from '../helpers/dateFromatter'
import { _getTime } from '../interfaces/types'

interface props {
  getTime: _getTime
}

const TimePicker: React.FC<props> = ({ getTime }) => {
  const { current: currentTime } = useRef(new Date())
  const [hour, setHour] = useState(currentTime.getHours())
  const [minute, setMinute] = useState(currentTime.getMinutes())
  const [second, setSecond] = useState(currentTime.getSeconds())
  const [time, setTime] = useState('00:00:00')

  const selectedTime = (t: string) => getTime(t)

  useEffect(() => {
    setTime(`${formatTime(hour)}:${formatTime(minute)}:${formatTime(second)}`)
    selectedTime(time)
  }, [hour, minute, second, time])

  const hourChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (+e.target.value > 23) {
      setHour(() => 23)
    } else if (+e.target.value < 0) {
      setHour(0)
    } else if (e.target.value === '') {
      setHour(0)
    } else {
      setHour(+e.target.value)
    }
  }

  const minuteChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (+e.target.value > 59) {
      setMinute(59)
    } else if (+e.target.value < 0) {
      setMinute(0)
    } else if (e.target.value === '') {
      setMinute(0)
    } else {
      setMinute(+e.target.value)
    }
  }

  const secondChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (+e.target.value > 59) {
      setSecond(59)
    } else if (+e.target.value < 0) {
      setSecond(0)
    } else if (e.target.value === '') {
      setSecond(0)
    } else {
      setSecond(+e.target.value)
    }
  }

  const hourUp = () => {
    setHour((prev) => prev + 1)
    if (hour + 1 > 23) {
      setHour(0)
    }
  }
  const hourDown = () => {
    setHour((prev) => prev - 1)
    if (hour - 1 < 0) {
      setHour(23)
    }
  }

  const minuteUp = () => {
    setMinute((prev) => prev + 1)
    if (minute + 1 > 59) {
      setMinute(0)
      hourUp()
    }
  }
  const minuteDown = () => {
    setMinute((prev) => prev - 1)
    if (minute - 1 < 0) {
      setMinute(59)
      hourDown()
    }
  }

  const secondUp = () => {
    setSecond((prev) => prev + 1)
    if (second + 1 > 59) {
      setSecond(0)
      minuteUp()
    }
  }
  const secondDown = () => {
    setSecond((prev) => prev - 1)
    if (second - 1 < 0) {
      setSecond(59)
      minuteDown()
    }
  }

  return (
    <div className={styles.timePicker} data-time={time}>
      <div className={styles.hour}>
        <div role="textbox" onClick={hourUp} className={styles.hrUp} />
        <input
          placeholder="00"
          type="number"
          className={styles.hr}
          value={hour}
          onChange={hourChange}
        />
        <div role="textbox" onClick={hourDown} className={styles.hrDown} />
      </div>

      <div className={styles.separator}>:</div>

      <div className={styles.minute}>
        <div role="textbox" onClick={minuteUp} className={styles.minUp} />
        <input
          placeholder="00"
          type="number"
          className={styles.min}
          value={minute}
          onChange={minuteChange}
        />
        <div role="textbox" onClick={minuteDown} className={styles.minDown} />
      </div>

      <div className={styles.separator}>:</div>

      <div className={styles.second}>
        <div role="textbox" onClick={secondUp} className={styles.secUp} />
        <input
          placeholder="00"
          type="number"
          className={styles.sec}
          value={second}
          onChange={secondChange}
        />
        <div role="textbox" onClick={secondDown} className={styles.secDown} />
      </div>
    </div>
  )
}

export default TimePicker
